version: "3.7"
services:
  account:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./:/app
    container_name: accounts_api_container
    expose:
      - "8080"
    ports:
      - "8080:8080"
    command: npm run dev

