version: "3.7"
services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./gateway:/app
    container_name: gateway_container
    expose:
      - "8080"
    ports:
      - 8080:8080
    command: npm run dev

  account:
    build:
      context: ./services/accounts
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./services/accounts:/app
    container_name: accounts_container
    expose:
      - "8080"
    command: npm run dev

  template:
    build:
      context: ./services/template
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./services/template:/app
    container_name: template_container
    expose:
      - "8080"
    command: npm run dev
