version: "3.7"
services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./gateway/src:/app/src
    container_name: gateway_container
    expose:
      - "8080"
    ports:
      - 8080:8080
    environment:
      WAIT_HOSTS: user:8080, template:8080
    command: sh -c "/wait && npm run dev"

  user:
    build:
      context: ./services/user
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./services/user/src:/app/src
    container_name: user_container
    expose:
      - "8080"
    command: npm run dev

  template:
    build:
      context: ./services/template
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./services/template/src:/app/src
    container_name: template_container
    expose:
      - "8080"
    command: npm run dev
