version: "3.7"
services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./src:/app/src
    container_name: gateway_api_container
    expose:
      - "8080"
    ports:
      - 8080:8080
    command: npm run dev
