version: "3.7"
services:
  user:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./src:/app/src
    container_name: user_api_container
    expose:
      - "8080"
    ports:
      - "8080:8080"
    command: npm run dev
